name: 'Clear File From Sucuri Cache'
description: 'Clears a specific file from the Sucuri cache'
inputs:
  api_key:
    description: 'Sucuri API Key'
    required: true
  api_secret:
    description: 'Sucuri API Secret'
    required: true
  file:
    description: 'Plugin file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Copy zip and readme files to GiveWP.com
      shell: bash
      run: |
        rsync -avz ${{ inputs.zip-file }} ${{ secrets.GIVEWP_DOWNLOADS_PATH }}/${{ inputs.plugin-slug }}.zip
        rsync -avz ${{ inputs.readme-file }} ${{ secrets.GIVEWP_DOWNLOADS_PATH }}/plugins/"${{ inputs.plugin-slug }}/readme.txt"

    - name: Clear file from Sucuri cache
      shell: bash
      run: curl 'https://waf.sucuri.net/api?v2' \
        --data 'k=${{ inputs.api_key }}' \
        --data 's=${{ inputs.api_secret }}' \
        --data 'a=clear_cache' \
        --data "file=${{ inputs.file }}"